In [3]:
import pandas as pd

data = pd.read_csv("/Users/brunoinzunza/Documents/GitHub/BAT/research/optimization_results_20251021_142655.csv")

data

,rank,sma_period,std_multiplier,train_pnl,train_trades,train_win_rate,val_pnl,val_trades,val_win_rate,test_pnl,test_trades,test_win_rate,avg_pnl,consistency
0,1,3,0.4,71721.14,5933,68.67,97.59,2889,66.11,38837.41,2986,68.29,19467.500,1.0
1,2,3,0.3,71120.27,6020,68.39,441.24,2929,66.13,38106.18,3028,67.73,19273.710,1.0
2,3,3,0.5,70249.04,5808,68.75,-516.51,2839,65.90,38464.28,2929,67.87,18973.885,0.0
3,4,4,1.5,70102.06,2755,70.20,5216.38,1353,66.08,34876.68,1378,69.09,20046.530,1.0
4,5,3,0.6,69910.99,5697,68.86,-851.32,2781,65.88,38669.59,2873,67.98,18909.135,0.0
5,6,3,0.2,69642.87,6078,67.95,-2597.32,2975,65.65,36246.23,3062,67.37,16824.455,0.0
6,7,4,0.5,69395.98,4951,69.88,-9928.25,2408,66.07,35573.95,2498,69.26,12822.850,0.0
7,8,4,0.7,69354.81,4652,69.93,-8644.00,2314,66.29,36202.79,2382,69.56,13779.395,0.0
8,9,3,0.1,69305.17,6152,67.91,-2807.00,3018,65.44,36615.98,3106,67.13,16904.490,0.0
9,10,4,0.6,69191.25,4787,69.96,-10209.16,2352,65.82,36881.13,2447,69.68,13335.985,0.0